<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HauntedHouse.ApplicationServices\HauntedHouse.ApplicationServices.csproj" />
    <ProjectReference Include="..\HauntedHouse.Core\HauntedHouse.Core.csproj" />
    <ProjectReference Include="..\HauntedHouse.Data\HauntedHouse.Data.csproj" />
  </ItemGroup>

</Project>
